import { PermissionAction, PermissionResource } from '@shared/enums';

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * Audit Log Permissions
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * READ only — entries are system-generated by `AuditLogRecorder` from other
 * modules' own business actions, never created/updated/deleted through this
 * resource directly. Matches the frontend's own `PERMISSIONS.AUDIT_LOGS_READ`
 * exactly (`frontend/src/config/permissions.config.ts` defines no
 * `AUDIT_LOGS_MANAGE`). Mirrors `modules/reports/constants/report.permissions.ts`.
 * ─────────────────────────────────────────────────────────────────────────────
 */
const RESOURCE = PermissionResource.AUDIT_LOGS;

export const AUDIT_PERMISSIONS = {
  READ: `${RESOURCE}:${PermissionAction.READ}`,
} as const;

export type AuditPermission = (typeof AUDIT_PERMISSIONS)[keyof typeof AUDIT_PERMISSIONS];
